import torch
import os
from openai import OpenAI
# Import configuration
from proj_src.utils.config import (
    MODEL_LIST, 
    JUDGE_MODEL_NAME, 
    ORIGINAL_PROMPT, 
    K_OUTPUTS_PER_MODEL, 
    MAX_ITERATIONS
)

# Import utility functions
from proj_src.utils.model_utils import (
    load_model_and_tokenizer, 
    generate_model_outputs, 
    get_judge_evaluation
)
from proj_src.utils.prompt_utils import (
    create_consensus_prompt, 
    update_prompts_from_feedback
)
def main():
    input = """
    Here is the question: If Marcy works for the same company for 40 years, she gets an annual pension of $50,000/year. Starting after 20 years, she becomes entitled to 5% of the value of the pension per year. If she quits after 30 years, what will her annual pension be?
    These are answers generated by some students. 
    <student 1> answered $34,166.67.. Here is the reasoning process for this answer: The first 20 years yield $50,000/year, totaling $1,000,000. The next 10 years yield 5% of $50,000/year, totaling $25,000. The total pension over 30 years is $1,025,000, divided by 30 years gives $34,166.67/year.
    <student 2> answered $55,333.33.. Here is the reasoning process for this answer: The first 20 years yield $50,000/year, totaling $1,000,000. The next 10 years yield 5% of $50,000/year, which is a geometric series with a first term of $2,500, a common ratio of 1.05, and 10 terms. The sum of the series is $660,000. The total pension over 30 years is $1,000,000 + $660,000 = $1,660,000. The total pension over 30 years is $1,660,000, divided by 30 years gives $55,333.33.
    <student 3> answered $52,820.74.. Here is the reasoning process for this answer: The first 20 years yield $50,000/year, totaling $1,000,000. The next 10 years yield a 5% annual increase starting from $50,000/year, calculated year by year. The sum of the next 10 years is $584,622.10. The total pension over 30 years is $1,000,000 + $584,622.10 = $1,584,622.10. The annual pension for 30 years is $1,584,622.10 / 30 years ≈ $52,820.74/year.
    Review each student's answer and select the answer you think is right. If you think all the answers are wrong, propose a new answer and give the reasoning process behind it. Your answer:"""


    # Load model and tokenizer
    tokenizer, model = load_model_and_tokenizer("google/gemma-3-4b-it")

    # Generate and collect outputs
    model_outputs = generate_model_outputs(
        model, 
        tokenizer, 
        input
    )
    del model, tokenizer
    torch.cuda.empty_cache()
    print(model_outputs)


if __name__ == "__main__":
    main()