import re
from proj_src.utils.config import MODEL_LIST
from proj_src.utils.output_utils import (
    extract_answer_solution
)

def create_summary_prompt(candidate_answer_output: str):
    summary_prompt = candidate_answer_output # candidate_answer_output contains original prompt
    summary_prompt += """

You are just a summarizer. Only use the input provided to you, and do not solve or reason about the answer even if it's not correct.
Please analyze the answer above and summarize the reasoning process for the answer derived.
Do not repeat the candidate answer or the question. 
Your final answer should be in the following JSON format:

{
  "solution": <single-string summary of derivation>,
  "answer": <single-number answer from input>
}
"""
    return summary_prompt

def create_consensus_prompt(original_prompt: str, candidate_answers: list):
    """
    Create a prompt for the judge model to evaluate consensus among candidate answers.
    
    Args:
        original_prompt (str): The original problem statement
        candidate_answers (list): List of candidate answers
        
    Returns:
        str: The prompt for the judge model
    """
    # Base prompt with original question and candidate answers
    prompt = '\n'.join(candidate_answers)
    prompt += """
Please analyze the candidate answers above and determine the most popular final answer and whether there is complete agreement.
Do not repeat the candidate answers or the question.
If there is no consensus on the candidate answers, output the most popular answer.
If all answers are different, select the best one.
Only use the output from the input given.
Your final answer should be in the following JSON format:

{
  "consensus": <are all the answers the same, true or false, as a bool>
  "final_answer": <most popular answer as a number>
}

"""
    
    return prompt

def update_prompts_from_feedback(original_prompt, previous_answers):
    """
    Extract feedback from judge response and update prompts for next iteration.
    
    Args:
        original_prompt (str): The original problem statement
        previous_answers (list): Summaries of previous model answers
        num_prompts (int): Number of prompts to return
        
    Returns:
        str: Updated prompt
    """
    
    new_prompt = f"Here is the question: {original_prompt}\nThese are answers generated by some students.\n"

    for i,json_summary in enumerate(previous_answers):
        answer,solution = extract_answer_solution(json_summary)
        new_prompt += f"<student {i+1}> answered {answer}. Here is the reasoning process for this answer: {solution}\n"
    
    new_prompt += "Review each student's answer and select the answer you think is right. If you think all the answers are wrong, propose a new answer and give the reasoning process behind it.\nYour answer:\n"

    return new_prompt
